# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1132c9a493a980e4795b6a2b1122397d9c2f08f3afa909d149382cfaf5ee53daaaef485a6644407ff7a97dcae2b37117106ac29080e620d74877852eb6d172ac

test:
  secret_key_base: 1d58a18a3d88e08d09443fc1d810ef0e0be7fac8eb22abe8c30010a71a07da55c64f2090127c27ba766fa392e6e0674de3b69d49f693cb2c127a5b54729b101a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
